while True:
    print("!!!비트겟 마진거래 계산기!!!")
    print("")
    print("")
    print("")
    print("1. $$$ 매매 정보 $$$")
    print("")
    A=float(input("    시드 총액을 입력하세요. : "))
    print("")
    B=float(input("    진입 총액을 입력하세요. : "))
    print("")
    C=float(input("    진입가격을 입력하세요. : "))
    print("")
    H=int(input("    포지션 입력해주세요(롱=1 or 숏=2): "))
    print("")
    D=float(input("    레버리지를 입력하세요. : "))
    print('')
    print("")
    E=(80/100)*A
    F=(B/A)*100
    print("2. $$$ 100% 진입시 청산 정보 $$$")
    print("")
    print("")
    print("    시드 총액 중 %f만큼 잃으면 청산입니다."%E)
    print("")
    print("    현재 진입총액은 시드 총액 대비%f 입니다."%F)
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    if H==1:
        print("정리!!!. $$$ %d"%F,"%"," 롱 진입시 청산 정보 $$$")
        print("")
        print("")
        G=C-(C*((96.5/D)*(96.5/F)))/100
        K=C-G
        print("포지션 = 롱",end="          ")
        print("")
        print("")
        print("")
        print("    총 시드 = %f"%A,end="          ")
        print("진입시드 = %f"%B,end="          ")
        print("")
        print("")
        print("")
        print("    진입비율 = %f"%F,end="          ")
        print("진입가격 = %f"%C,end="          ")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("        현 코인에서의 청산가 변동폭 :    %f"%K)
        print("")
        print("")
        print("")
        print("        현 진입비율에서의 청산가    :    %f"%G)
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        
    else:
        print("정리!!!. $$$ %d"%F,"%"," 숏 진입시 청산 정보 $$$")
        print("")
        print("")
        G=C+(C*((96.5/D)*(96.5/F)))/100
        K=G-C
        print("포지션 = 롱",end="          ")
        print("")
        print("")
        print("")
        print("    총 시드 = %f"%A,end="          ")
        print("진입시드 = %f"%B,end="          ")
        print("")
        print("")
        print("")
        print("    진입비율 = %f"%F,end="          ")
        print("진입가격 = %f"%C,end="          ")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("        현 코인에서의 청산가 변동폭 :    %f"%K)
        print("")
        print("")
        print("")
        print("        현 진입비율에서의 청산가    :    %f"%G)
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
